### ISSUE TITLE
111 111 11. 11. 1111?

### ISSUE THREAD

**Issue by 10-cookies** [H-Doyle/1#1]
1,111,11,1. 11?
`
111 1111
     11 111 11
1111 11 1
111 1
11 111111 1
`
111,11 1111111 11, 11. 1111?

**Comment by H-Doyle** [comment]
> 

1111111? 111. 1111.

**Comment by 10-cookies** [comment]
11111! 1111 111 11 111111 11 1 1 1 11, 11 11 111,  1111 11, 1111 1, 11111111! 11
